# Generated by Django 3.2.6 on 2021-09-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210917_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='brithday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
