# Generated by Django 3.2.6 on 2021-09-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_profile_brithday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='brithday',
            new_name='birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
    ]
