# Generated by Django 3.2.6 on 2021-10-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='follower',
        ),
    ]
