# Generated by Django 3.2.6 on 2021-10-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_replay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_replay', to='home.comment'),
        ),
    ]
