# Generated by Django 3.2.6 on 2021-10-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211014_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_replay',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replay',
        ),
    ]
